### PR TITLE
Remove unused definitions

### PR DESCRIPTION
**Pull request by tschmittni**
Just removing unused definitions to fix some warnings.

### CODE REVIEW

**Review by pvallone — CHANGES_REQUESTED** [review]
These definitions need to stay, even though they aren't used. Swagger doesn't provide a way to document a WebSocket API, so all we can do is add definitions for the available WebSocket actions.

**Comment by tschmittni** [comment]
I wouldn't add the WebSocket-related parts at all. Swagger doesn't support WebSockets at the moment which makes this rather useless.

**Comment by pvallone** [comment]
We document how to open a WebSocket connection in Swagger, and reference the action objects in the description for that route. I agree that they're useless in that you can't do WebSocket stuff in Swagger UI, or in generated clients, but you can at least view the schema for the actions, and our thinking was that that was better than nothing.

**Comment by spanglerco** [comment]
We also intend to support websockets in our codegen for services.

**Comment by tschmittni** [comment]
alright, sounds good.

**Pull request closed without merging**
