### PR TITLE
TestMonitor | Adding TestMonitor OpenAPI document for SLE

### PR DESCRIPTION
**Pull request by Madhan-Reddy-ni**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/systemlink-OpenAPI-documents/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Recently as a part of this feature - [Feature 2092223](https://ni.visualstudio.com/DevCentral/_workitems/edit/2092223): Add keywords and properties to steps, we have added new properties (`keywords` and `properties`) to steps. We want to add these new properties to OpenAPI documents which lets users to create steps with the right set of properties. While updating the [old version of document](https://github.com/ni/systemlink-OpenAPI-documents/blob/master/test-monitor/nitestmonitor-v2.yml) we found that it hadn't been updated for a long time and updating it doesn't feel right considering SLS. So, we went ahead with creating a new folder named `SLE` inside test-monitor and placed the latest document from the skyline repo. 

### Why should this Pull Request be merged?

In this PR, we have added the latest swagger documentation of test-monitor service for SLE which will help users in making API calls to the service with the right set of properties.

### What testing has been done?

Tested in [Swagger Editor](https://editor.swagger.io/)

### CODE REVIEW

**Review by MuthuRajan-S — APPROVED** [review]
LGTM.

**Comment by MuthuRajan-S** [comment]
I talked with Richard Bell about this, since these changes are SLE specific and the current documents are outdated and new SLE changes are not there, we proceed with creating a new document for SLE.

**Comment by adamarnesen** [comment]
Can you please highlight what the changes are from what is currently shipping with SLE? I don't want to re-review all of the code. In fact, it would be best to have 2 PRs. One that is just a copy of the current docs and another with the diffs.

**Review by adamarnesen — CHANGES_REQUESTED** [review]
Can you please highlight what the changes are from what is currently shipping with SLE? I don't want to re-review all of the code. In fact, it would be best to have 2 PRs. One that is just a copy of the current docs and another with the diffs.

**Comment by Madhan-Reddy-ni** [comment]
> Can you please highlight what the changes are from what is currently shipping with SLE? I don't want to re-review all of the code. In fact, it would be best to have 2 PRs. One that is just a copy of the current docs and another with the diffs.

Hi @adamarnesen 

I have updated the PR just to contain current/older SLE swagger document, I will be creating one more PR adding keywords and properties inside steps. Currently, the [PR](https://github.com/Madhan-Reddy-ni/systemlink-OpenAPI-documents/pull/2) is created inside the Forked Repo because of some limitations with the Forked Repo we will raise it main repo once this PR got completed.

**Review by adamarnesen — APPROVED** [review]

**Review by CiprianAnton — APPROVED** [review]

**Pull request merged**
