### PR TITLE
Push changes for SystemLink 19.5

### PR DESCRIPTION
**Pull request by spanglerco**
- [x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/systemlink-OpenAPI-documents/blob/master/CONTRIBUTING.md).

### What does this Pull Request accomplish?

Updates the public repository with the latest OpenAPI documents for the SystemLink 19.5 release.

### Why should this Pull Request be merged?

Ensures the latest documentation is up to date.

### What testing has been done?

Looked at the diff and the diff of our local subtree.

### CODE REVIEW

**Comment by spanglerco** [comment]
Due to the test monitor document rename, I plan to temporarily remove it from api.systemlinkcloud.com and then add it back with the V2 API after submitting this PR.

**Review by alexweav — APPROVED** [review]

**Review by rares-pop — APPROVED** [review]
LGTM!

**Review by vdeac — APPROVED** [review]
for Asset Management related yml

**Comment by tschmittni** [comment]
Can you update helium-documentation?
https://github.com/ni-kismet/helium-documentation/blob/master/bin/build.sh#L16

Currently, the build is failing:
cp: cannot stat 'node_modules/@ni-kismet/systemlink-openapi-documents/test-monitor/nitestmonitor.yml': No such file or directory

https://travis-ci.com/ni-kismet/helium-documentation/builds/131349328

**Pull request merged**
